In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("datasets/video_games.csv")
# Mostrar las Primeras 5 filas del dataset
df.head()

,Title,Features.Handheld?,Features.Max Players,Features.Multiplatform?,Features.Online?,Metadata.Genres,Metadata.Licensed?,Metadata.Publishers,Metadata.Sequel?,Metrics.Review Score,...,Length.Main + Extras.Average,Length.Main + Extras.Leisure,Length.Main + Extras.Median,Length.Main + Extras.Polled,Length.Main + Extras.Rushed,Length.Main Story.Average,Length.Main Story.Leisure,Length.Main Story.Median,Length.Main Story.Polled,Length.Main Story.Rushed
0,Super Mario 64 DS,True,1,True,True,Action,True,Nintendo,True,85,...,24.916667,29.966667,25.000000,16,18.333333,14.333333,18.316667,14.500000,21,9.700000
1,Lumines: Puzzle Fusion,True,1,True,True,Strategy,True,Ubisoft,True,89,...,9.750000,9.866667,9.750000,2,9.616667,10.333333,11.083333,10.000000,3,9.583333
2,WarioWare Touched!,True,2,True,True,"Action,Racing / Driving,Sports",True,Nintendo,True,81,...,3.850000,5.666667,3.333333,11,2.783333,1.916667,2.933333,1.833333,30,1.433333
3,Hot Shots Golf: Open Tee,True,1,True,True,Sports,True,Sony,True,81,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
4,Spider-Man 2,True,1,True,True,Action,True,Activision,True,61,...,12.766667,17.316667,12.500000,12,10.483333,8.350000,11.083333,8.000000,23,5.333333

In [5]:
# Nombre de todas las colum
df.columns

Index(['Title', 'Features.Handheld?', 'Features.Max Players',
       'Features.Multiplatform?', 'Features.Online?', 'Metadata.Genres',
       'Metadata.Licensed?', 'Metadata.Publishers', 'Metadata.Sequel?',
       'Metrics.Review Score', 'Metrics.Sales', 'Metrics.Used Price',
       'Release.Console', 'Release.Rating', 'Release.Re-release?',
       'Release.Year', 'Length.All PlayStyles.Average',
       'Length.All PlayStyles.Leisure', 'Length.All PlayStyles.Median',
       'Length.All PlayStyles.Polled', 'Length.All PlayStyles.Rushed',
       'Length.Completionists.Average', 'Length.Completionists.Leisure',
       'Length.Completionists.Median', 'Length.Completionists.Polled',
       'Length.Completionists.Rushed', 'Length.Main + Extras.Average',
       'Length.Main + Extras.Leisure', 'Length.Main + Extras.Median',
       'Length.Main + Extras.Polled', 'Length.Main + Extras.Rushed',
       'Length.Main Story.Average', 'Length.Main Story.Leisure',
       'Length.Main Story.Median', 'Length.Main Story.Polled',
       'Length.Main Story.Rushed'],
      dtype='object')

In [11]:
df["Release.Year"]

# Filtrar juegos lanzados desde el año 2000
juegos_2000 = df[df['Release.Year'] >= 2000]

# Ordenar por ventas descendente el TOP 5 
top_5 = juegos_2000.sort_values(by='Metrics.Sales', ascending=False).head(5)

# Mostrar el TOP 5 
top_5[['Title', 'Release.Year', 'Metrics.Sales']]

                     Title  Release.Year  Metrics.Sales
156               Wii Play          2006          14.66
833         Mario Kart Wii          2008          12.39
157  New Super Mario Bros.          2006          10.03
22           Mario Kart DS          2005           9.99
23              Nintendogs          2005           9.72